title: "My Jekyll Website"
description: "This is my Jekyll website description."
url: "https://yiwenmo.github.io/myiwen.github.io/"
baseurl: /
theme: jekyll-theme-minimal
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
plugins:
  - jekyll-feed
  - jekyll-sitemap

