name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages # 若gh_pages有異動則觸發

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Set up Node.js
        uses: actions/setup-node@v2 # 設立Node.js
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install 

      - name: Build
        run: npm run build 

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push
