name: Sync HackMD Notes to Blog

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Taipei
      
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install requests
      run: pip install requests

    - name: Run HackMD sync script
      run: python scripts/hackmd_sync.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add _posts || echo "No changes"
        git commit -m "Auto-sync HackMD notes" || echo "No changes to commit"
        git push origin main


